services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Mount current directory, so that it will automatically update
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
