FROM node:24-alpine3.21

# Add user
RUN adduser -D -u 1001 app
USER 1001
WORKDIR /app

# Copy package.json and package-lock.json only
COPY package*.json ./

# Install dev dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

ENV NODE_ENV=development
EXPOSE 3000

CMD ["npm", "run", "dev"]
